name: 'Run D-Scanner with reviewdog'
description: '🐶 Run D-Scanner with reviewdog on pull requests to improve code review experience.'
author: 'Samuel El-Borai'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'

  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review]'
    default: 'github-pr-review'

  ### Flags for D-Scanner ###
  path:
    description: 'Root directory where D-Scanner should be run from'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'triangle'
  color: 'red'
