name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / dscanner (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_WORKSPACE: ./testdata
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / dscanner (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_WORKSPACE: ./testdata
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / dscanner (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_WORKSPACE: ./testdata
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
